context.properties = {
    link.max-buffers = 16
    default.clock.rate = 96000
    default.clock.allowed-rates = [ 44100 48000 88200 96000 ]
    default.clock.quantum = 16
    default.clock.min-quantum = 16
    default.clock.max-quantum = 1024
}
