#!/usr/bin/env bash
set -e

if [ "$#" -ne 1 ]; then
    echo "Usage: workvm-run 'command'"
    exit 2
fi

ssh workvm "$1"

# Fedora ~/.ssh/config
#
# Host workvm
#     HostName 192.168.122.177
#     User yakov
#     IdentityFile ~/.ssh/ylopatin_id_ed25519
#     IdentitiesOnly yes
