bind r source-file /home/yaquochi/.config/tmux/tmux.conf \; display-message "Config reloaded!"
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g mouse on
set -g set-clipboard on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"

# Theme: purple mint
set -ogq @thm_bg "#15111f"
set -ogq @thm_fg "#9cffdf"

set -ogq @thm_mint "#9cffdf"
set -ogq @thm_green "#8fffc1"
set -ogq @thm_teal "#89dceb"
set -ogq @thm_slate "#8d94aa"
set -ogq @thm_purple "#c792ea"
set -ogq @thm_purple_dark "#2a213a"
set -ogq @thm_red "#d26a7c"
set -ogq @thm_yellow "#f5a6d6"
set -ogq @thm_blue "#8ab4f8"

set -g status-position top
set -g status on
set -g status-style "bg=#9ccfcf,fg=#15111f"

set -g window-status-style "bg=#9ccfcf,fg=#3a3448"
set -g window-status-current-style "bg=#3a2f4f,fg=#9cffdf,bold"

set -g pane-border-style "fg=#2a213a"
set -g pane-active-border-style "fg=#c792ea"

set -g message-style "bg=#4b3d66,fg=#9cffdf"
set -g mode-style "bg=#4b3d66,fg=#ffffff"
